### ISSUE TITLE
buffer释放

### ISSUE THREAD

**Issue by wongzhichao** [lostleaf/binance_tick_parser#1]
`void open_file_check(const std::string& snap_path, const std::string& update_path)
    {
        input_snap_ = fopen(snap_path.c_str(), "r");
        input_update_ = fopen(update_path.c_str(), "r");
        auto buf = new char[1000];

        fscanf(input_snap_, "%s", buf);
        if (std::string(buf) != HEADER)
            throw std::runtime_error("Snapshot header not match");

        fscanf(input_update_, "%s", buf);
        if (std::string(buf) != HEADER)
            throw std::runtime_error("Update header not match");

        delete buf;
    }`

1. buffer是字节数组，delete应该按照数组释放
2. 当有异常的时候，不会被释放，引起内存泄露

**Comment by lostleaf** [comment]
这个方法确实不太好，我换成了 std::string
